### ISSUE TITLE
READMEの内容確認依頼

### ISSUE THREAD

**Issue by tom03p** [tom03p/syn-on#1]
READMEを作成いたしましたので、内容の確認をお願い致します。

**Comment by kenchasonakai** [comment]
内容を確認できないのでissueではなくプルリクエストを作成して、Files changedにREADME.mdの内容がすべて入るように調整後ご提出をお願いします

**Comment by tom03p** [comment]
承知いたしました。
プルリクエストの方で作成し直します。
